{{- if and .Values.kafkaConnect.enabled .Values.postgresql.enabled .Values.oracle.enabled }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: jdbc-sink-oracle-to-pg
  namespace: {{ .Values.namespaces.kafka }}
  labels:
    strimzi.io/cluster: kafka-connect
    app.kubernetes.io/name: jdbc-sink
    app.kubernetes.io/part-of: kafka-demo
    app.kubernetes.io/managed-by: Helm
  annotations:
    argocd.argoproj.io/sync-wave: "55"
spec:
  class: io.debezium.connector.jdbc.JdbcSinkConnector
  tasksMax: 1
  config:
    topics: oracle.DEBEZIUM.CUSTOMERS
    connection.url: "jdbc:postgresql://postgresql.{{ .Values.namespaces.kafka }}.svc:5432/{{ .Values.postgresql.database }}"
    connection.username: {{ .Values.postgresql.user }}
    connection.password: demo-password-123
    insert.mode: upsert
    primary.key.mode: record_key
    primary.key.fields: ID
    delete.enabled: true
    schema.evolution: basic
    table.name.format: oracle_customers
    key.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: true
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: true
{{- end }}
