quarkus.http.port=8080

kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:kafka-cluster-kafka-bootstrap:9092}

mp.messaging.incoming.orders-in.connector=smallrye-kafka
mp.messaging.incoming.orders-in.topic=orders
mp.messaging.incoming.orders-in.value.deserializer=com.redhat.demo.kafka.OrderDeserializer
mp.messaging.incoming.orders-in.auto.offset.reset=earliest
mp.messaging.incoming.orders-in.group.id=order-consumer
mp.messaging.incoming.orders-in.failure-strategy=ignore

quarkus.package.jar.type=uber-jar
