apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.kafka }}
  labels:
    app.kubernetes.io/part-of: kafka-demo
    app.kubernetes.io/managed-by: Helm
  annotations:
    argocd.argoproj.io/sync-wave: "5"
