quarkus.http.port=8080

kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:kafka-cluster-kafka-bootstrap:9092}

mp.messaging.outgoing.orders-out.connector=smallrye-kafka
mp.messaging.outgoing.orders-out.topic=orders
mp.messaging.outgoing.orders-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.orders-out.key.serializer=org.apache.kafka.common.serialization.StringSerializer

quarkus.package.jar.type=uber-jar
