ingressDomain: ""

namespaces:
  kafka: kafka-demo

amqStreams:
  enabled: true
  channel: stable

kafka:
  enabled: true
  replicas: 3
  storage:
    size: 10Gi
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 4Gi

apicurio:
  enabled: true
  channel: "3.x"

kafkaConnect:
  enabled: false

postgresql:
  enabled: false

oracle:
  enabled: false

apps:
  producer:
    enabled: false
  consumer:
    enabled: false
