ingressDomain: ""
repoUrl: ""

namespaces:
  kafka: kafka-demo

amqStreams:
  enabled: true
  channel: stable

kafka:
  enabled: true
  replicas: 3
  storage:
    size: 10Gi
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 4Gi

apicurio:
  enabled: true
  channel: "3.x"

kafkaConnect:
  enabled: true
  replicas: 1
  debezium:
    postgresVersion: "3.6.1.Final"
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 2Gi

postgresql:
  enabled: true
  database: demodb
  user: demouser
  image: "postgresql:12-el8"
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 512Mi

oracle:
  enabled: false

apps:
  producer:
    enabled: true
    replicas: 1
    contextDir: apps/producer
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: "1"
        memory: 512Mi
  consumer:
    enabled: true
    replicas: 1
    contextDir: apps/consumer
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: "1"
        memory: 512Mi
